apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-app
  template:
    metadata:
      labels:
        app: auth-app
    spec:
      containers:
      - name: auth-app
        image: bentennison/auth-service:latest
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 50051
        - containerPort: 35580
---
apiVersion: v1
kind: Service
metadata:
  name: auth-app-service
spec:
  type: NodePort
  selector:
    app: auth-app
  ports:
  - name: grpc
    port: 30051
    targetPort: 30051
    nodePort: 31052
  - name: http
    port: 30580
    targetPort: 30580
    nodePort: 31580
